### ISSUE TITLE
Error 404 in links in README

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/powerShell-Docs.pt-br#3]
_From @CeciAc on October 22, 2018 18:8_

@IgorRozani commented on [Fri Oct 19 2018](https://github.com/PowerShell/powerShell-Docs.pt-br/issues/2)

In the section [Contribuindo](https://github.com/PowerShell/powerShell-Docs.pt-br#contribuindo), in the README.md has two links that are not working, they are linking two files that doesn't exist in the project.

![image](https://user-images.githubusercontent.com/802968/47239407-9b246980-d3bb-11e8-8f02-9ca5547f9668.png)

The first link is "guia de contribuições", that refers to a CONTRIBUTING.md that doesn't exist.
The second is "guia de estilo", that refers to a STYLE.md that doesn't exist.

---

@CeciAc commented on [Fri Oct 19 2018](https://github.com/PowerShell/powerShell-Docs.pt-br/issues/2#issuecomment-431507338)

Hello, @IgorRozani

Thank you for your feedback. 
We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

_Copied from original issue: PowerShell/PowerShell-Docs#3149_

**Comment by nokura** [comment]
Dear @sdwheeler 
Thank you for your contribution. I am taking action to fix the issue. I will get back to you when we implement the latest README.md in the repo
Best Regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @nokura 
Any updates on this?
best

**Comment by CeciAc** [comment]
Hi @nokura
Any updates on this?
best

**Comment by CeciAc** [comment]
Hi @nokura
Any updates on this?
best
@DavidPrio fyi

**Comment by nokura** [comment]
I am sorry for my late reply. The issue has been solved on Oct 29th. Please let me close this issue.
The link goes to [https://github.com/PowerShell/powerShell-Docs.pt-br/blob/live/CONTRIBUTING.md](https://github.com/PowerShell/powerShell-Docs.pt-br/blob/live/CONTRIBUTING.md)
![pt-br_404error-fixed](https://user-images.githubusercontent.com/13804190/49174068-3e8d6600-f2fa-11e8-9c1d-92cbae686198.PNG)
